Token=90091783787325686:0:abZ8bIuktjqYQ2XlsIf09ig6Pr0rxs
URI=wss://d1.nandbox.net:5020/nandbox/api/
DownloadServer=https://d1.nandbox.net:5020/nandbox/download/
UploadServer=https://d1.nandbox.net:5020/nandbox/upload/